# Generated by Django 5.2.12 on 2026-04-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogcategory_contactinquiry_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('doc_file', models.FileField(help_text='The actual certificate (PDF or Image)', upload_to='certificates/')),
                ('badge_icon', models.ImageField(blank=True, help_text='Sleek 3D icon for the gallery', null=True, upload_to='achievements/badges/')),
                ('category', models.CharField(help_text='e.g., AI, CyberSecurity, Web Development', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
    ]
